### ISSUE TITLE
It takes ~20 seconds to be done - too long

### ISSUE THREAD

**Issue by zalexua** [norbertkiszka/rigol-screenshot#1]
Not an issue, but too long.

You could investigate how print-screen.html page on DH800 series is doing.
It takes literally 450 ms for full session, from request till fully getting 250KB Jpeg data.

**Comment by norbertkiszka** [comment]
You mean that screenshot from webpage is faster than this script? DHO800 and DHO900 series has very slow response to SCPI requests - which is done here. It's just a very bad design in those series.

Querying model number will also take some time, so probably it will be better idea to hardcode model by ip in some config file.

**Comment by zalexua** [comment]
ohh, actually data (BMP) transfer happens immediately and takes just 300ms, but the script is spending +20 seconds because you have hardcoded "-w 20" for "netcat" commad. 
This is not so smart ...

I've decreased the value to 1 (a minimum) and it can successfully capture screenshot, in 1.57 seconds in total for script execution time.
